name: Deploy on cliping.softopark.com
on:
  workflow_dispatch:
# on:
#   push:
#     branches: [ dev ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: 
          username: ec2-user
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo systemctl stop clipingpath.service
            cd clippingpathsindia
            git pull
            sudo systemctl start clipingpath.service